### ISSUE TITLE
Find Dataset to Showcase COVID-19 Case Numbers + Sources/Outbreaks

### ISSUE THREAD

**Issue by Suri111200** [Software-For-Love/vaccine-dashboard#3]
Estimated Time: 2-3h

- Determine whether there is an API that can be used to retrieve this data regularly (since it constantly changes)
- Determine what sort of information exactly can be shown with respect to Case Source/Outbreaks
-  Make a note of whether we can find data on a day-by-day basis (ie. if the data can say "On January 1, 2021, there were x number of cases, and y number were from these sources")
- Must show data that can be divided into public health units (for example, if it's split by Forward Sortation areas or Census subdivisions, find out if there is a way to merge rows in such a way that they constitute one PHU.)
- If possible, query the data source and store results in the form of a .csv or .xls/.xlsx

Please present your findings at the team meeting on Friday! DM me or respond to this issue and add @Suri111200 if you have any questions/concerns.

**Comment by Suri111200** [comment]
@NutanNimkar Please add the link to your API as a comment here! Close the issue once you're done.

**Comment by NutanNimkar** [comment]
https://art-bd.shinyapps.io/covid19canada/ this is Covid-19 API.
This is the dataset source for # of cases https://github.com/ccodwg/Covid19Canada
