### ISSUE TITLE
Find Dataset to Showcase COVID-19 Vaccination Statistics

### ISSUE THREAD

**Issue by Suri111200** [Software-For-Love/vaccine-dashboard#4]
Estimated time: 3h

- Determine whether there is an API that can be used to retrieve this data regularly (since it constantly changes)
- Determine what sort of information exactly can be shown with respect to Case Numbers
- Must show data that can be divided into public health units (for example, if it's split by Forward Sortation areas or Census subdivisions, find out if there is a way to merge rows in such a way that they constitute one PHU.)
- Make a note of whether we can find statistics on a day-by-day basis or not (ie. whether the source can tell you something like "On January 1, 2021, there were x number of vaccinations")
- If possible, query the data source and store results in the form of a .csv or .xls/.xlsx

**Comment by Suri111200** [comment]
@AvaneeshM Please add a link to your API here! Close the issue once you're done.

**Comment by AvaneeshM** [comment]
https://api.covid19tracker.ca/docs/1.0/overview
